{% set name = "rnc2rng" %}
{% set version = "2.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rnc2rng-{{ version }}.tar.gz
  sha256: 5a01d157857b5f010a94167e7092cc49efe2531d58e013f12c4e60b8c4df78f1

build:
  entry_points:
    - rnc2rng = rnc2rng.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - rply

test:
  source_files:
    - test.py
    - tests
  imports:
    - rnc2rng
  commands:
    - pip check
    - python test.py
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/djc/rnc2rng
  summary: RELAX NG Compact to regular syntax conversion library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxb2
